ranks = {
{[RANK] = "GEN CMND", [USERS] = "109827200"},
{[RANK] = "CMND", [USERS] = "nil"},
{[RANK] = "LT CMND", [USERS] = "nil"},
{[RANK] = "HI. MARSH", [USERS] = "nil"},
{[RANK] = "MARSH", [USERS] = "nil"},
{[RANK] = "CAPT", [USERS] = "nil"},
{[RANK] = "CHIEF LT.", [USERS] = "nil"},
{[RANK] = "LT. 1C", [USERS] = "nil"},
{[RANK] = "LT. 2C", [USERS] = "nil"},
{[RANK] = "ENSIGN", [USERS] = "nil"},
{[RANK] = "COM. SGT", [USERS] = "nil"},
{[RANK] = "SGT. MAJ", [USERS] = "nil"},
{[RANK] = "1ST SGT", [USERS] = "nil"},
{[RANK] = "SGT", [USERS] = "nil"},
{[RANK] = "CPL", [USERS] = "nil"},
{[RANK] = "1ST PRIVATE", [USERS] = "nil"},
{[RANK] = "PRIVATE", [USERS] = "nil"},
{[RANK] = "RECRUIT", [USERS] = "nil"},
  
}
